import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Divider from "@/components/Divider";

// Google font
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// Local fonts
const athina = localFont({
  src: "./fonts/FontsFree-Net-AthinaRegular-ywAy3.ttf",
  variable: "--font-athina",
});

const hormond = localFont({
  src: [
    {
      path: "./fonts/Harmond-SemiBoldCondensed.otf",
      style: "normal",
      weight: "600",
    },
    {
      path: "./fonts/Harmond-ExtraBoldExpanded.otf",
      style: "normal",
      weight: "800",
    },
  ],
  variable: "--font-avenir-next",
});

export const metadata: Metadata = {
  title: "Landing Restaurent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${inter.variable} 
          ${athina.variable} 
          ${hormond.variable} 
          antialiased
        `}
      >
        <Header />
        <main className="bg-[#0E0D0A] min-h-screen">{children}</main>
        <Divider type="without-logo" />
        <Footer />
      </body>
    </html>
  );
}
